"""add_department_missing_columns

Revision ID: d655c4631338
Revises: 0007_department_score
Create Date: 2026-07-12 15:58:54.175465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd655c4631338'
down_revision: Union[str, None] = '0007_department_score'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_app_settings_key', type_='unique')
        batch_op.drop_index('ix_app_settings_key')
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('carbon_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_index('ix_carbon_transactions_department_id')
        batch_op.drop_index('ix_carbon_transactions_emission_factor_id')
        batch_op.drop_index('ix_carbon_transactions_source_record_id')
        batch_op.drop_index('ix_carbon_transactions_transaction_date')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='dept_status'), nullable=False))
        batch_op.add_column(sa.Column('head_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_departments_head_id', 'users', ['head_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('environmental_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_environmental_goals_department_id')

    with op.batch_alter_table('product_esg_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_esg_profiles_product_id', type_='unique')
        batch_op.drop_index('ix_product_esg_profiles_product_id')
        batch_op.create_index(batch_op.f('ix_product_esg_profiles_product_id'), ['product_id'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_sku', type_='unique')
        batch_op.drop_index('ix_products_sku')
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.create_index('ix_products_sku', ['sku'], unique=False)
        batch_op.create_unique_constraint('uq_products_sku', ['sku'])

    with op.batch_alter_table('product_esg_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_esg_profiles_product_id'))
        batch_op.create_index('ix_product_esg_profiles_product_id', ['product_id'], unique=False)
        batch_op.create_unique_constraint('uq_product_esg_profiles_product_id', ['product_id'])

    with op.batch_alter_table('environmental_goals', schema=None) as batch_op:
        batch_op.create_index('ix_environmental_goals_department_id', ['department_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('head_id')
        batch_op.drop_column('status')
        batch_op.drop_column('employee_count')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('carbon_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_carbon_transactions_transaction_date', ['transaction_date'], unique=False)
        batch_op.create_index('ix_carbon_transactions_source_record_id', ['source_record_id'], unique=False)
        batch_op.create_index('ix_carbon_transactions_emission_factor_id', ['emission_factor_id'], unique=False)
        batch_op.create_index('ix_carbon_transactions_department_id', ['department_id'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.create_index('ix_app_settings_key', ['key'], unique=False)
        batch_op.create_unique_constraint('uq_app_settings_key', ['key'])

    # ### end Alembic commands ###
